import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		// System.out.println(new App().getGreeting());
		Game g = new Game(6);
		g.marca("1", Set.of(Card.DAGGER, Card.CONSERVATORY, Card.LOUNGE));
		g.addSuggest(new Suggest("1", "4", Card.MISS_SCARLETT, Card.CANDLESTICK, Card.DINING_ROOM, Card.CANDLESTICK));
		g.addSuggest(new Suggest("3", "6", Card.MISS_SCARLETT, Card.ROPE, Card.BALLROOM, null));
		g.addSuggest(new Suggest("5", "1", Card.PROFESSOR_PLUM, Card.DAGGER, Card.CONSERVATORY, null));
		g.addSuggest(new Suggest("6", "1", Card.MRS_PEACOCK, Card.REVOLVER, Card.LOUNGE, null));
		g.addSuggest(new Suggest("1", "2", Card.MRS_WHITE, Card.REVOLVER, Card.BALLROOM, Card.REVOLVER));
		g.addSuggest(new Suggest("2", "4", Card.MISS_SCARLETT, Card.CANDLESTICK, Card.DINING_ROOM, null));
		System.out.println("ok");
	}
}
